### ISSUE TITLE
digitizeImages broken in R 4.2.0

### ISSUE THREAD

**Issue by Ax3man** [aaronolsen/StereoMorph#12]
In R 4.2.0, `if()` statements with a condition of length greater than one give an error rather than a warning.

This means `digitizeImages` no longer saves landmarks to disk, since `list2XML4R` is now broken. This is caused by the same problem as #8. Checking for classes using `class(x) == "logical"` will yield a logical vector of length 2 when `x` is e.g. a matrix (since matrices have both the `"matrix"` and `"array"` class). The solution is to check for classes using `is.` functions (like `is.logical`, `is.character` etc.) or to use `inherits(x, 'logical')`.

Installing #9 solves the problem for me.

**Comment by aaronolsen** [comment]
Thank you so much Wouter for keeping on top of this and I'm sorry that I've fallen so behind on this! I made the change in the source files and on Github but never got around to merging your branch or updating the version on CRAN. I've now merged your branch and I've uploaded an updated version to CRAN. So a new version should be available in a couple of days. I'll try my best to merge branches and update the CRAN version more quickly in the future!

**Comment by Ax3man** [comment]
No worries! It only _just_ broke (it was just warnings before), and I had a working version anyways. But good to hear it's on its way to CRAN!

Thanks again for the package, I use `digitzeImages` almost daily, and it's lovely to be able to annotate landmarks directly from R. It works very well!

**Comment by aaronolsen** [comment]
That's so great to hear! Glad it's useful!
