### ISSUE TITLE
TPSToShapes file format and question

### ISSUE THREAD

**Issue by Lampichthys** [aaronolsen/StereoMorph#4]
Hi Aaron, I'm sorry if this question has already been addressed elsewhere. I am trying to use the TPSToShapes code on a dataset of about 800 specimen images (which is why I would prefer not to have to set landmarks on every image again in StereoMorph). The homologous landmark coordinates in my TPS output files, as far as I can tell, are never named, but the conversion code requires the names of each landmark, understandable for the conversion process. My first question is, am I missing something from TPS that allows the naming of landmarks, or should I manually name them? My second question is, if I have to perform this manually, what should the format be (names delimited by tabs before X and Y coordinates, some other method)? 

I am really looking forward to using StereoMorph in the future and will use it regardless of if I need to re-digitize all 800 images in the process, but wanted to see if you had any input.

Thanks in advance!

Rene

**Comment by aaronolsen** [comment]
Hi Rene,

Thanks for the question! You're not missing anything in TPS. With TPS you don't have to (or can't I believe) name the landmarks. You have to maintain a separate list of the landmark names in the same order as the landmarks are listed in the TPS file.

To name the landmarks with the conversion process you don't have to change the TPS files at all. You just input the landmark names when you run the TPSToShapes function via the 'landmark.names' parameter. 'landmark.names' can be either a vector of landmark names, for example:

c('lm01', 'lm02', 'lm03')

or a text file (extension .txt) with each of the landmark names listed on a separate line, like:

lm01
lm02
lm03

I've updated the manual entry for TPSToShapes to clarify this so it will be updated in the next CRAN upload. Let me know if you run into any more issues!

Aaron
