### ISSUE TITLE
Trouble Saving in Digitizing Window

### ISSUE THREAD

**Issue by cchessher** [aaronolsen/StereoMorph#7]
Hi, I'm having an issue working in RStudio on PC. When I open the image digitizing window, the save button is not available to select and automatically saving any landmark edits doesn't work either. I don't believe it's an issue with my working directory because saving works correctly for a tutorial I have saved under the same Box folder. Also, I've tried downloading the images from Box and moving them to a local folder to attempt saving that way with no luck.

**Comment by aaronolsen** [comment]
Hi @cchessher - thanks for posting this! I'm not sure what the problem could be. Typically the 'Save' button is grayed out if there's no save location provided in the function call. Or potentially the save location provided doesn't exist (though I think that should give a warning or error). If that isn't the problem then I'll have to reproduce the problem on my system to track down the issue. If you'd like for me to try that could you attach the minimum necessary files and R command you used so I can try it out?

As a note I don't test StereoMorph for RStudio - only for R console. I know people have been using it in RStudio without issue. I'm guessing/hoping it's not something particular to RStudio.
